<br /><br />
<div id="view-content">
	<div class="gallery" align="center">
		
		<div class="thumbnails">
			<img onmouseover='preview.src=img1.src' name="img1" src='<?php echo $this->baseUrl('img/1.jpg')?>' alt="" />
			<img onmouseover="preview.src=img2.src" name="img2" src='<?php echo $this->baseUrl('img/2.jpg')?>' alt="" />
			<img onmouseover="preview.src=img3.src" name="img3" src=<?php echo $this->baseUrl('img/3.jpg')?> alt="" />
			<img onmouseover="preview.src=img4.src" name="img4" src=<?php echo $this->baseUrl('img/4.jpg')?> alt="" />
		</div>
		
		<div class="preview" align="center">
			<img name="preview" src=<?php echo $this->baseUrl('img/1.jpg')?> alt=""/>
		</div>
	</div>
</div>