<div id="srodek_info" style=" margin-left: -40px; width:630px;">
        <?php 
        $IDUzytkownik=$this->IDUzytkownik;
     
isset($_POST['data']) ? $data = $_POST['data'] : $data = $_GET['data'];

   
    $tory= $this->iloscTorow;
    $ilosc_torow=$tory[0]['Ilosc_Torow'];

        echo "<h3>Rezerwacje dla dnia: </h3><h2>".$data."</h2>";
        $dataZ = new Zend_Date();
        $dataZ->set($data);
     
        $dzienTygodnia= $dataZ->get(Zend_Date::WEEKDAY_DIGIT);
      
        
        $db = Zend_Db_Table::getDefaultAdapter(); 
        $sql="SELECT * FROM godziny_otwarcia WHERE DzienTygodnia LIKE ".$dzienTygodnia ;
        $otwarty = $db-> query($sql)->fetchAll();
       
        
       // print_r($otwarty);
  
        //Godziny zajęte
       //$db1 = Zend_Db_Table::getDefaultAdapter(); 
        $data_format=date("Y-m-d", strtotime($data));
        
        //print_r($zajete_terminy);
       
        $od= date("H:i", strtotime($otwarty[0]['GodzinaOtwarcia']));
        $do= date("H:i", strtotime($otwarty[0]['GodzinaZamkniecia']));
        $czas=$do-$od;
        //print_r($czas);
        $akk=$od;
 
for($j=1;$j<=$ilosc_torow;$j++){
 echo 
 "<table class='rezerwacja'>
    <tbody>
        <tr><td class='first_row'><a href=".$this->baseUrl('img/b'.$j.'.jpg')." target='_blank'>TOR ".$j."</a></td>";
        
        
   //Pobranie zajętych terminów dla konkretnego toru.
            $sql_zajete="SELECT Distinct(`DataCzas`) AS unikalne, TIME(DataCzas) AS Godzina, Date(DataCzas) AS Data, 
               `TorPreferowany` ,  `CzyNaWylacznasc`, count(*) AS ZarezerwowaneMiejsca
              FROM rezerwacja WHERE DATE(DataCzas) LIKE '".$data_format."' AND
                    TorPreferowany = ".$j." AND `CzyOdwolana` =0 
               GROUP BY DataCzas";

            $zajete_terminy[$j]=$db->query($sql_zajete)->fetchAll();
           // print_r($zajete_terminy);
            $now=date("Y-m-d H:i:s");
             $plus=date("Y-m-d H:i:s", strtotime($now .' + 1 hours') );
           $datetime_check=$data_format." $akk:00";
            
            
              
          for($i=1;$i<=$czas;$i++){
            $data_time=$data."/".$akk;
            //sprawdzenie czy dany termin nie jest już zajęty 
            $moznaRezerwowac=true;
            $datetime_check=$data_format." $akk:00";
            
        //sprawdzenie godziny
          
            $nie_dostepne= false;  
                
            $zajete = false;
           
           if($datetime_check<$plus){
              $nie_dostepne=true;
               echo "<td class='termin'><strong>$akk</strong></td>";
               $akk = date('H:i', strtotime($akk . ' + 1 hours')); 
              }
           else{   
            for($z=0;$z<sizeof($zajete_terminy[$j]);$z++){
              $zajeta_godzina= date("H:i", strtotime($zajete_terminy[$j][$z]['Godzina']));
                
                if($akk==$zajeta_godzina){
                    $zajete = true;
                    $czas_zajete=$data_format." ".$akk.":00";
                    if(czyZajeteGodzina($IDUzytkownik,$czas_zajete,$j)>0){
                         echo "<td class='masz-rezerwacje'><a href='".$this->baseUrl('/rezerwacja/index/?data='.$data.'?'.$akk.'?'.$j)."'>".$akk."</a></td>";
                    }
                    else{
                        if($zajete_terminy[$j][$z]['CzyNaWylacznasc']==1 OR 
                        $zajete_terminy[$j][$z]['ZarezerwowaneMiejsca']>2){
                            echo "<td class='zajete'>".$akk."</a></td>";
                        }
                        else{
                            echo "<td class='zajete_nieWylacznosc'>
                                        <a href='".$this->baseUrl('/rezerwacja/index/?data='.$data.'?'.$akk.'?'.$j)."'>".$akk."</a></td>";
                        }
                    }
                    break;
                }
            }
       if (!$zajete) {
          echo "<td class='wolny'><a href='".$this->baseUrl('/rezerwacja/index/?data='.$data.'?'.$akk.'?'.$j)."'>".$akk."</a></td>";
        }
              $akk = date('H:i', strtotime($akk . ' + 1 hours')); 
    }
 }
      echo"</tr>
    </tbody>
 </table>";
$akk=$od;          
}
        ?>
        <p>Legenda:</p>
        <p><table id="legenda">
            <tbody>
                 <tr>
                    <td class='termin'> </td>
                    <td>Termin zapisów minął</td>
                </tr>
                <tr>
                    <td class='wolny'> 
                    </td><td>Wolny</td>
                    
                </tr>
                <tr>
                    <td class='zajete'> </td>
                    <td>Zajęty</td>
                </tr>
                <tr>
                    <td class='zajete_nieWylacznosc'> </td>
                    <td>Zarezerwowany nie na wyłączność</td> 
                    
                </tr>
                <tr>
                    <td class='masz-rezerwacje'> </td>
                    <td>Masz rezerwacje w tym terminie</td> 
                    
                </tr>    
                   
               
            </tbody>
            </tbody>
        </table></p>

</div>

<div id="srodek_view2" style="{position: relative; width: 450px;}">
			<br><b>PLAN BASENU:</b><br>
			<img src='<?php echo $this->baseUrl('img/ball.jpg')?>' width="450" height="300">
			</div>
<?php

function czyZajeteGodzina($IDUzytkownik,$data_time,$tor){
            if($IDUzytkownik){
                $sql="SELECT COUNT(*) AS ilosc FROM rezerwacja where uzytkownik_idUzytkownik LIKE $IDUzytkownik AND 
                   DataCzas LIKE '".$data_time."' AND CzyOdwolana LIKE 0 AND TorPreferowany LIKE ".$tor.""  ;
                    $db=Zend_Db_Table_Abstract::getDefaultAdapter();
                    $rezerwacja=$db->query($sql)->fetchAll();
                    $czyRezewacjGodzina=$rezerwacja[0]['ilosc'];
                   return $czyRezewacjGodzina;
                }
                else{
                    $czyRezerwacjaGodzina=null;
                return $czyRezerwacjaGodzina;
                }
        }
    ?>