<div id="srodek_info">
	<h2>Co nas wyróżnia</h2>
	<ul>
	    <li>Możliwość rezerwacji miejsc na basenie</li>
	    <li>Gwarancja dogodnego korzystania z basenu</li>
	    <li>Wgląd do historii wizyt na basenie</li>
	    <li>Atrakcyjne ceny!</li>
	</ul>
	<br><br>
	
	
	
</div>

<div id="srodek_view">
	<h2>Aktualności</h2><br>
	<br>
	<h3>40 medali dla naszych pływaków</h3>
	<br>17-19 czerwca na gliwickim basenie „Olimpijczyk” odbyła się druga edycja zawodów najważniejszych dla polskich pływaków. 
	<br>Były to Letnie Otwarte Mistrzostwa Polski Masters.<br><br><br>
	<h3>Dzieci płacą mniej!!!</h3>
	<br>Bilety dla dzieci 50% taniej na BASEN od poniedziałku do piątku w godzinach 11:00, 12:00, 13:00.
	<br>Serdecznie zapraszamy!<br><br><br>
	<h3>Praca na basenie!</h3>
	<br>Poszukujemy ratowników WOPR do pracy na basenie!<br>
</div>

