<div id="srodek_info">
	<h2>Co nas wyróżnia</h2>
	<ul>
	    <li>Możliwość rezerwacji miejsc na basenie</li>
	    <li>Gwarancja dogodnego korzystania z basenu</li>
	    <li>Wgląd do historii wizyt na basenie</li>
	    <li>Atrakcyjne ceny!</li>
	</ul>
	<br><br>
	
	
	
</div>

<div id="srodek_view">
	<h2>Aktualności</h2><br>
	<br>
        <?php
        $wynik=$this->wynik;
        
        for($k=0;$k<sizeof($wynik);$k++){
            $dataArray = explode("-", $wynik[$k]['Data']);
            $dataEUformat = empty($wynik[$k]['Data']) ? "" : $dataArray[2] . "." + $dataArray[1] . "." . $dataArray[0];
        
            echo "<small>".$dataEUformat."</small> <h3>".$wynik[$k]['naglowek']."</h3>";
            echo "<p>".$wynik[$k]['tresc']."</p>";
        }
        ?>
	
</div>

