<h2>O NAS</h2>
<br><br>
Pływalnia DELFINEK jest jednym z najnowocześniejszych obiektów o charakterze sportowo - rekreacyjnym. 
Obiekt mieści się we Wrocławiu na bulwarze Słonecznym. 
Na wszystkich spragnionych ruchu i relaksu czekają baseny.

<br><br>
<b>Zaawansowane technologie</b>
<br>
W DELFINKU zastosowano szereg innowacyjnych rozwiązań technologicznych, które zapewniają wysoką funkcjonalność obiektu.
Nadzór nad prawidłowym działaniem wszystkich urządzeń wspiera elektroniczny system. 
Jakość wody jest jednym z najważniejszych elementów eksploatacji pływalni. Czterokrotna w ciągu doby wymiana pracującej w obiegu zamkniętym wody, 
pozwala na utrzymanie wysokich norm czystości. 
<br><br>
<b>Komfort dla wszystkich</b>
<br>
Klimatyzacja oraz utrzymywanie w halach basenowych temperatury powietrza wyższej od temperatury wody 
zapewnia pływającym poczucie komfortu. 
Nowoczesny zespół szatni i natrysków pozwala Klientom na wygodne przygotowanie się do korzystania
ze wszystkich wodnych atrakcji.
Wykwalifikowana kadra ratowników i instruktorów oraz personel DELFINKA dbają o bezpieczeństwo i dobre samopoczucie Klientów.
<br><br><br>
Do DELFINKA warto wybrać się o każdej porze roku. <br>
<br><br>
<b>Zapraszamy od poniedziałku do piątku, od 8:00 do 20:00, oraz w weekendy od 10:00 do 18:00!</b>
