<br /><br />
<?php 

if(isset($this->registrationForm)) { 
    echo "<h2>Formularz rejestracyjny</h2>";
    echo $this->registrationForm; }
else { echo "<h2>Gratulujemy!</h2> <p>Rejestracja przebiegła poprawnie! Możesz teraz zalogować się do systemu.</p>"; 
        echo "<p><a href='".$this->baseUrl('klient/index')."'Przejdzi do logowania</p>";
}

// if(isset($this->idUzytkownik)) { echo $this->idUzytkownik; }
?>