<div id="srodek_info" style=" margin-left: -40px; width:630px;">
<?php 
        $IDUzytkownik=$this->IDUzytkownik;
        $url="http://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];

	    $tmp = explode('/', $url);
	    //print_r($tmp);
	    $data=$tmp[7];
	    $tory= $this->iloscTorow;
	    $ilosc_torow=$tory[0]['Ilosc_Torow'];

        echo "<h3>Rezerwacje dla dnia: </h3><h2>".$data."</h2>";
        $dataZ = new Zend_Date();
        $dataZ->set($data);
     
        $dzienTygodnia= $dataZ->get(Zend_Date::WEEKDAY_DIGIT);
      	
        $db = Zend_Db_Table::getDefaultAdapter(); 
        $sql="SELECT * FROM godziny_otwarcia WHERE DzienTygodnia LIKE ".$dzienTygodnia ;
        $otwarty = $db-> query($sql)->fetchAll();
       
  		$data_format=date("Y-m-d", strtotime($data));
        
        $d=date("d", strtotime($data));
        $m=date("m", strtotime($data));
        $r=date("Y", strtotime($data));
        
		//echo 'dddd '.$d.'.'.$m.'.'.$r;
		
		$od= date("H:i", strtotime($otwarty[0]['GodzinaOtwarcia']));
        $do= date("H:i", strtotime($otwarty[0]['GodzinaZamkniecia']));
        $czas=$do-$od;
        
        $akk=$od;
 		
 		$sql_uzyt="SELECT TIME(DataCzas) AS Godzina, Date(DataCzas) AS Data, 
	            `TorPreferowany`, `Imie` AS Imie, `Nazwisko` as Nazwisko, idUzytkownik, CzyJest,
	            idRezerwacja
	       		FROM rezerwacja 
	       		JOIN klient ON klient.idUzytkownik = rezerwacja.uzytkownik_idUzytkownik
	       		WHERE DATE(DataCzas) LIKE '".$data_format."'";
	
		$uzytkownicy=$db->query($sql_uzyt)->fetchAll();
		
		//print_r($uzytkownicy);
		//print_r(' rozmiar: ');
		//print_r(sizeof($uzytkownicy));
		//print_r(' '.$uzytkownicy[0]['Godzina']);
		
		for($j=1;$j<=$ilosc_torow;$j++){
			echo 
		 	"<table class='rezerwacja_r' width='1000px'>
		    	<tbody>
		        	<tr>
		        		";
		        
		        
		   				//Pobranie zajętych terminów dla konkretnego toru.
			            $sql_zajete="SELECT Distinct(`DataCzas`) AS unikalne, TIME(DataCzas) AS Godzina, Date(DataCzas) AS Data, 
			               `TorPreferowany` ,  `CzyNaWylacznasc`, count(*) AS ZarezerwowaneMiejsca
			              FROM rezerwacja WHERE DATE(DataCzas) LIKE '".$data_format."' AND
			                    TorPreferowany = ".$j." AND `CzyOdwolana` =0 
			               GROUP BY DataCzas";
			
		    	        $zajete_terminy[$j]=$db->query($sql_zajete)->fetchAll();
		        	   
		        	   	if($zajete_terminy[$j]){
		        	   		echo "<td class='first_row_r'>TOR ".$j."</td>";
		        	   	
				          for($i=1;$i<=$czas;$i++){
				            $data_time=$data."/".$akk;
				            //sprawdzenie czy dany termin nie jest już zajęty 
				            
				            $zajete = false;
				           
				            for($z=0;$z<sizeof($zajete_terminy[$j]);$z++){
				              $zajeta_godzina= date("H:i", strtotime($zajete_terminy[$j][$z]['Godzina']));
				                if($akk==$zajeta_godzina){
				                    $zajete = true;
				                    $czas_zajete=$data_format." ".$akk.":00";
				                    
				                    echo "<td class='normal' width='150px'><b>".$akk."</b><br>";
				                    	
				                    	$id_box=0;
				                    			
				                    	for($u=0;$u<sizeof($uzytkownicy);$u++){
				                    		if($uzytkownicy[$u]['Godzina']==$akk.":00" &&
				                    			$uzytkownicy[$u]['TorPreferowany'] == $j){
				                    				
												$jest_id = $uzytkownicy[$u]['idUzytkownik'];
												$jest_r = $uzytkownicy[$u]['idRezerwacja']; //id rezerwacji
												
												if($uzytkownicy[$u]['CzyJest'] == 0){
												
												
												echo "
					                        	<input type='button' id='button".$id_box."'
					                        		name='box".$id_box."' class='button_e'
					                        		value='".$uzytkownicy[$u]['Imie']." ".$uzytkownicy[$u]['Nazwisko']."'				                        
					                        		onclick='myFunction(".$jest_r.",".$d.",".$m.",".$r.")
					                        	'>
					                        	</input>
					                        	<br>
												";
												
												
												}
												else{
					                        	echo "
					                        	<input type='button' disabled='disabled' class='button_d'
					                        	value ='".$uzytkownicy[$u]['Imie']." ".$uzytkownicy[$u]['Nazwisko']."'>
					                        	</input>
					                        	<br>
												";
												}
												}
											$id_box++;
										}
				                    echo "</td>";
									break;
				                }//end if($akk)
				            }//end for($z)
				       
				              $akk = date('H:i', strtotime($akk . ' + 1 hours')); 
				    }//end for($i)
				    } //end if($zajete_terminy)
				      echo"</tr>
				    </tbody>
				 </table>
				 
        ";
				$akk=$od;          
				}//end for($j)
		    echo "<p>Legenda:</p>
        <p><table id='legenda'>
            <tbody>
                <tr>
                    <td class='nieobecny'> 
                    </td><td>Nieobecny</td>
                    
                </tr>
                <tr>
                    <td class='obecny'> </td>
                    <td>Obecny</td>
                </tr>
            </tbody>
            </tbody>
        </table></p>"
		    ?>

<script>
	function myFunction(jest_r, d,m,r){
		var data=d+'.'+m+'.'+r;
	window.location = "/PZ_SRP/public/recepcja/czyjest/IDRezerwacja/"+jest_r+"/Data/"+data;
	}
</script>
