<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
  <head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->headMeta() ?>
     
      <?php echo $this->headLink() 
                ->prependStylesheet($this->baseUrl('css/style.css'));
       //         ->appendStylesheet($this->baseUrl('js/jquery-ui-1.9.1.custom/jquery-ui-1.9.1.custom/css/sunny/jquery-ui-1.9.1.custom.mini.css'));
              
    
?>

<!--[if lt IE 8]>
            <?php echo $this->headLink() 
                ->prependStylesheet($this->baseUrl('css/styleIE.css'));?>
        <![endif]-->

	<title>DELFINEK</title>
  </head>
<body>
<div id="header">
	<div id="header_log">
             <li><a href="<?php echo $this->baseUrl('klient')?>">LOGOWANIE</a></li>
             <li><a href="<?php echo $this->baseUrl('index/rejestracja')?>">REJESTRACJA</a></li>
    </div>
</div>
<div id="h_p">
<div id="head">
	
    <div id="logo">
    	<img src=<?php echo $this->baseUrl('img/logo3.jpg')?> style="position: absolute"></img>
    </div>
    
    <div id="menu">
    	<ul id="menuglowne">
	            <li><a href="<?php echo $this->baseUrl('index/index')?>">HOME</a></li>
	            <li><a href="<?php echo $this->baseUrl('index/onas')?>">O NAS</a></li>
	            <li><a href="<?php echo $this->baseUrl('index/kalendarz')?>">REZERWACJA</a></li>
	            <li><a href="<?php echo $this->baseUrl('index/cennik')?>">CENNIK</a></li>
	            <li><a href="<?php echo $this->baseUrl('index/galeria')?>">GALERIA</a></li>
	            <li><a href="<?php echo $this->baseUrl('index/kontakt')?>">KONTAKT</a></li>
		</ul>
    </div>    
</div>
</div>
    <div id="srodek">
		<div id="nav">
			<?php echo $this->navigation() ?>
  		</div>

		<div id="pojemnik">
    		<?php echo $this->layout()->content; ?>
	    </div>
    </div>
        
	<div id="footer">
		© 2013 Delfinek - Projekt zespołowy
	</div>
</body>
</html>
