<?php
$idKlient= $this->idKlient;
foreach ($this->dane as $klient):?>

<?php echo

"
    <h1>Dane klienta</h1>

            <p>Imię:". $klient['Imie']."</p>
            <p>Nazwisko:". $klient['Nazwisko']."</p>";
            //<p>Telefon:". $klient['Telefon']."</p>"
            //<p>Mail:". $klient['Mail']."</p>";
   
echo "<p><a href='".$this->url(array( 'action'=>'dane-edit', 'id'=>$idKlient))."' class='button'>Edytuj</a> </p>";
?>
<?php endforeach;
  ?>
