<h2>Witaj w systemie!</h2>
        <p>Jesteś zalogowany jako <strong>Klient</strong></p>.
<?php 
  
         $ZendDate= new Zend_Date();
         $data= $ZendDate->get(Zend_Date::DATETIME_MEDIUM);

         $data_format=date("Y-m-d H:i:s", strtotime($data));
         $IDUzytkownik=$this->IDUzytkownik;
         
         $urodziny=$this->urodziny;
         if(isset($urodziny[0]['DataUrodzenia'])){
             echo " <div id='urodziny'><p><img src='".$this->baseUrl('img/icon/urodziny.jpg')."' alt='życzenia urodzinowe'/></p>
                <p >  W związku z Twoimi urodzinami chcieliśmy Ci życzyć wszystkiego dobrego, dużo zdrowia, szczęścia oraz spełnienia marzeń.<p> 
                 <p id='small'>Zespół pływalni Delfinek</p></div>";
         }
         
         
         
       $najblizsze_zaplanowane=NajblizszeRezerwacje($IDUzytkownik,$data_format,0);
       $najblizsze_odwolane=NajblizszeRezerwacje($IDUzytkownik,$data_format,1);
       
       
       //Wyświetlanie najbliższych zaplanowanych wizyt
     if(sizeof($najblizsze_zaplanowane)>0){
         echo "<p class='info'> Twoja najbliższa zaplanowana wizyta jest na <strong>".$najblizsze_zaplanowane[0]['DataCzas']."</strong></p>";
     }
     else{
         echo "<p class='info'> Nie masz żadnych zaplanowanych wizyt.</p>";
     }

     //wyświetlanie najbliższych odwołanych wizyt
     if(sizeof($najblizsze_odwolane)>0){
         echo "<p class='error-box'> Twoja najbliższa odwołana wizyta była zaplanowana na <strong>".$najblizsze_odwolane[0]['DataCzas']."</strong>.</p>";
     }
     
     
function NajblizszeRezerwacje($IDUzytkownik,$data_format,$odwolane){
            if($IDUzytkownik){
                $sql="SELECT * FROM rezerwacja where uzytkownik_idUzytkownik LIKE $IDUzytkownik AND 
                   DataCzas >='".$data_format."' AND CzyOdwolana LIKE '".$odwolane."' ORDER BY DataCzas";
                    $db=Zend_Db_Table_Abstract::getDefaultAdapter();
                    $rezerwacja=$db->query($sql)->fetchAll();
                   return $rezerwacja;
                }
                else{
                    $rezerwacja=null;
                return $rezerwacja;
                }
        }
 
?>