<?php 
$IDRezerwacja=9;?>

<script>
function myFunction()
{
var x;
var id="<?php echo $IDRezerwacja; ?>";
var r=confirm("Czy jesteś pewny, że chcesz odwołać rezerwację?");
if (r==true)
  {
  x="<p class='confirm-box'>Dokonano usunięcia rezerwacji</p>";
     window.location.href="<?php echo $this->baseUrl('klient/odwolaj-rezerwacje/IDRezerwacja/')?>" +id;
  }
else
  {
  x="<p class='info'>Anulowano usuwanie rezerwacji</p>";
  }
document.getElementById("informacje").innerHTML=x;
}
</script>
<?php 

echo " <button onclick='myFunction()'>Odwołaj</button>";
echo "<p id='informacje'></p>";


?>
