<?php
// echo "<table><thead>";
//echo "<tr><th>ID</th><th>Taryfa</th><th>Cena</th><th>Typ</th><th>Czy na wyłączność</th><tr>";
//echo "</thead>";
//foreach($this->cennik as $row) {
//    echo "<tr><td>".$row['idCennik']."</td><td>".$row['Taryfa']."</td>";
//    echo "<td>".$row['Cena']."</td><td>".$row['OsobaTyp']."</td>";
//    echo "<td>".($row['CzyWylacznosc'] == 1 ? "tak" : "nie")."</td></tr>";
//    echo "<br/>";
//}
//echo "</table>";
echo "<h2>Edycja cennika</h2>";
echo $this->editCennikForm;
?>