
<?php

$data=$this->data;
$time=$this->time;
$tor=$this->tor;

//Sprawdzenie czy dany termin nie jest zajęty (wylacznosc 1 lub ilosc rezerwacji>2)
$data_format=date("Y-m-d", strtotime($data));
$data_time= $data_format." ".$time.":00";

 $db = Zend_Db_Table::getDefaultAdapter();
 $sql_zajete="SELECT Distinct(`DataCzas`) AS unikalne, TIME(DataCzas) AS Godzina, Date(DataCzas) AS Data, 
               `TorPreferowany` ,  `CzyNaWylacznasc`, count(*) AS ZarezerwowaneMiejsca
              FROM rezerwacja WHERE DataCzas LIKE '".$data_time."' AND
                    TorPreferowany =".$tor." AND`CzyOdwolana` =0 
               GROUP BY DataCzas";
 $zajety_termin=$db->query($sql_zajete)->fetchAll();
      if(isset($zajety_termin[0]['Data']) && ($zajety_termin[0]['CzyNaWylacznasc']==1 
              OR $zajety_termin[0]['ZarezerwowaneMiejsca']>2)){
          echo "<div class='error-box'><p><strong>Wybrany termin (".$data_time.") został już zarezerwowany.</strong></p></div>";
      }
 //---------------------------------------------------
     else{  
          $poczatek= date("h:i:s", strtotime($time));
          $next=date("h:i:s", strtotime($time)+3600);
   
         
          //echo $next;

             
      
//Godziny otwarcia basenu
        $dataZ = new Zend_Date();
        $dataZ->set($data);
        $dzienTygodnia= $dataZ->get(Zend_Date::WEEKDAY_DIGIT);
        $db = Zend_Db_Table::getDefaultAdapter(); 
        $sql="SELECT GodzinaZamkniecia FROM godziny_otwarcia WHERE DzienTygodnia LIKE ".$dzienTygodnia ;
        $otwarty = $db-> query($sql)->fetchAll();
        $koniec=$otwarty[0]['GodzinaZamkniecia'];
        //---------------------------------------------------
      
 //Sprawdzenie następnego zarezerwowanego terminu
      
         $sql_unikalne="SELECT Distinct(`DataCzas`) AS unikalne, TIME(DataCzas) AS Godzina, Date(DataCzas) AS Data, 
               `TorPreferowany` ,  `CzyNaWylacznasc`, count(*) AS ZarezerwowaneMiejsca
              FROM rezerwacja WHERE DATE(DataCzas) LIKE '".$data_format."' AND
                    TorPreferowany =".$tor." AND`CzyOdwolana` =0 AND
                    Time(DataCzas) BETWEEN '".$next."' AND '".$koniec."'
               GROUP BY DataCzas";
       
           $unikalne_godziny=$db->query($sql_unikalne)->fetchAll();
           $znalezione=false;
           
         //print_r($unikalne_godziny);
           
           
         for($t=0;$t<sizeof($unikalne_godziny);$t++){           //dla wszystkich uniklanych godzin rezerwacji
             if($poczatek.":00" < $unikalne_godziny[$t]['Godzina'] &&
                ($unikalne_godziny[$t]['CzyNaWylacznasc']==1  OR
                 $unikalne_godziny[$t]['ZarezerwowaneMiejsca']>2) AND 
                    $znalezione == false){
                 $znalezione=true;
                 $max_czas=$unikalne_godziny[$t]['Godzina'];
                 
             }
             
         }  
         
   if ($znalezione==true){
    $dlugosc_czasu=$max_czas-$poczatek.":00";
   }	
   
   else{
     $dlugosc_czasu=$koniec-$poczatek;
   }
       
     

           
 //Wyświetlenie formularza rezerwacji          
          echo "<h2> Rezerwacja basenu dla dnia $data</h2>";

$form=$this->form;
if(isset($zajety_termin[0]['CzyNaWylacznasc'])){
    $ile_osob_jest=$zajety_termin[0]['ZarezerwowaneMiejsca'];
                echo "<div class='info'><p><strong>Na Torze ".$tor." w wybranym dniu zarezerwowano już ".$ile_osob_jest." miejsce/a. 
                        Zatem nie ma możliwości rezerwacji tego toru na wyłączność</strong></p></div>";
    $form->CzyNaWylacznosc->setAttribs(array('disable' => 'disable'));
                
}
 
$czasTrwania=array();
           for($a=1;$a<=$dlugosc_czasu;$a++){
           $czasTrwania[$a]=$a;
           $form->IleRezerwacji->addMultiOption($a,$a);
           }
           
       

   $form->setAction($this->baseUrl('/rezerwacja/rezerwacja-zapis'));
 
    $form->Poczatek->setValue($poczatek);
    $form->TorPreferowany->setValue($tor);
    $form->IloscOsob->setValue(1);
    $form->CzyOdwolana->setValue(0);
    $form->CzasTrwania->setValue(1);
    
    //$form->IleRezerwacji->setOptions(array("1"=>"1", "2"=>"2"));
    
    
    $form->uzytkownik_idUzytkownik->setValue($this->IDUzytkownik);
   //$form->IleRezerwacji->setmultiOptions(array("1"=>"1", "2"=>"2"));
   $form->DataCzas->setValue($data_time);
    
      echo $form;
      
      
      }
//------------------------------------      
?>
