<?php
    $rowCount = count($this->rezerwacje);
    
    if($rowCount == 0) {
        echo "Nie dokonałeś żadnych rezerwacji na nadchodzące terminy";
    }
    else {
        echo "<table>";
        echo "<thead><tr><th>Data</th><th>Godzina</th><th>Tor</th><th>Ilość osób</th>";
        echo "<th>Czas trwania</th><th>Na wyłączność?</th></tr></thead>";
        echo "";
        echo "";
        echo "";
        echo "";
        
        foreach($this->rezerwacje as $row) {
            $dataCzas = Zend_Locale_Format::getDate($row['DataCzas'], 
                array('date_format' => 'yyyy-MM-dd HH:mm:ss'));
            
            echo "<tr>";
            echo "<td>" . $dataCzas['day'] ."." . $dataCzas['month'] . "." . $dataCzas['year'] . "</td>";
            echo "<td>" . $dataCzas['hour'] . ":" . $dataCzas['minute'] . "</td>";
            echo "<td>" . $row['TorPreferowany'] . "</td>";
            echo "<td>" . $row['IloscOsob'] . "</td>";
            echo "<td>" . $row['CzasTrwania'] . "</td>";
            echo "<td>" . ($row['CzyNaWylacznasc'] == 1 ? "<b>TAK</b>" : "nie") . "</td>";
            echo "</tr>";
            //echo print_r($row, true);
        }
    }
?>